### ISSUE TITLE
Initiating a GLOSSARY.md file in this repo to have a document with definition of "DDD"-related terms

### ISSUE THREAD

**Issue by Mehdi-H** [Mehdi-H/DDD-blue-book-collaborative-reading#7]
> :bulb: What do you think of initiating a GLOSSARY.md file in this repo to have a document with definition of "DDD"-related terms ?

Great idea. I made a [pull request](https://github.com/Mehdi-H/DDD-blue-book-collaborative-reading/pull/6) following your suggestion.

_Originally posted by @sofcalca in https://github.com/Mehdi-H/DDD-blue-book-collaborative-reading/discussions/3#discussioncomment-5687247_

**Comment by sofcalca** [comment]
I initiated the glossary, but only defined one term. Please feel free to complete it.
